# Render.com configuration
services:
  - type: web
    name: tactical-site
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  # Configure manualmente no dashboard

